### ISSUE TITLE
dmtcp: cannot open output channel for error logging

### ISSUE THREAD

**Issue by MrPrezident** [dmtcp/dmtcp#368]
I'm having trouble running dmtcp_coordinator on certain machines. I'm getting the following error:

```
dmtcp: cannot open output channel for error logging
dmtcp_coordinator starting...
    Host: badhost (1.2.3.4)
    Port: 7779
    Checkpoint Interval: disabled (checkpoint manually instead)
    Exit on last client: 0
```

After that, the dmtcp_coordinator hangs and doesn't respond to any commands. I am able to run dmtcp_coordinator successfully on other hosts, and I'm not sure what the difference is between the machines. The one that is failing happens to be an interactive LSF job, but if I use a different LSF pool it works fine, so I'm assuming that's not the issue.

**Comment by jiajuncao** [comment]
@MrPrezident The error indicates that it fails to open the internal file descriptor for logging. The default error logging fd is 827. Normally this won't happen: this is during the initialization phase of the coordinator, where no other code has come into play. One guess I can make is the system has certain limit on the number of fds one process can have, and if is smaller than 827, open()/dup()/dup2() would fail. What is your command to start the coordinator by the way?

**Comment by MrPrezident** [comment]
I just executing the dmtcp_coordinator command with no options.

**Comment by MrPrezident** [comment]
Are you referring to this? (From /proc/$pid/limits)

Limit                     Soft Limit           Hard Limit           Units     
Max open files            256                  1024                 files

**Comment by jiajuncao** [comment]
Yes, and I think that is the cause of your issue.
`ulimit -Sn 1024` should solve it.

**Comment by MrPrezident** [comment]
Hmm... I need to figure out how to do that on my system. I get "ulimit: Command not found."

**Comment by MrPrezident** [comment]
ulimit is a bash command, so I switched to bash shell (I was using tcsh). I ran the ulimit command that you mentioned. Now I'm seeing this:

```
[21577] ERROR at dmtcp_coordinator.cpp:1873 in main; REASON='JASSERT(listenSock->isValid()) failed'
     thePort = 7779
     (strerror((*__errno_location ()))) = Address already in use
Message: Failed to create listen socket.
If msg is "Address already in use", this may be an old coordinator.
Kill default coordinator and try again:  dmtcp_command -q
If that fails, "pkill -9 dmtcp_coord", and try again in a minute or so.
dmtcp_coordinator (21577): Terminating...
```

**Comment by MrPrezident** [comment]
oops! nvm. I had another dmtcp_coordinator already running. I guess it was blocking the port. I killed the other dmtcp_coordinator and started it. Now it is working! Thanks!

**Comment by MrPrezident** [comment]
I'm still having issues with the application that I'm running. It crashes when I try to create a checkpoint. I suspect that it is related to one of these limits (maybe stack size?) Do any of these limits look problematic to you?

```
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            134217728            134217728            bytes     
Max core file size        0                    0                    bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             6000                 6000                 processes 
Max open files            1024                 1024                 files     
Max locked memory         32768                32768                bytes     
Max address space         162276827136         162276827136         bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       1031705              1031705              signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     0                    0    
```                


Here are the limits on a different machine where the checkpoint is not crashing:
```
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            unlimited            unlimited            bytes     
Max core file size        0                    unlimited            bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             500                  500                  processes 
Max open files            1024                 1024                 files     
Max locked memory         32768                32768                bytes     
Max address space         5120000000           5120000000           bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       773435               773435               signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     0                    0                    

```

**Comment by jiajuncao** [comment]
It's hard to tell at this point. What's the error message when you do a checkpoint?

**Comment by MrPrezident** [comment]
There is no error message. It the application just exits. Should I try strace?

**Comment by MrPrezident** [comment]
I figured it out! It looks like the problem is the stack size. There is a hard limit set on the stack size on the interactive queue on LSF. When I ssh into the same machine, the stacksize hardlimit is unlimited and I am able to save a checkpoint without crashing. The application that I am running automatically tries to set the soft limit to unlimited, but it is unable to do so on the lsf interactive pool due to the hard limit set by the LSF configuration. Looks like I'll have to talk to somebody to see if I can get the hard limit removed.

**Comment by rohgarg** [comment]
@MrPrezident: If this has been resolved, could you please close this issue?
